#!/bin/bash

# Demo script for aicom interactive commit feature

echo "🎬 AIcom Interactive Commit Demo"
echo "================================="
echo ""
echo "How it works:"
echo ""
echo "1. AI generates a commit message"
echo "2. Message appears pre-filled in the prompt"
echo "3. You can:"
echo "   - Press ENTER to commit as-is"
echo "   - Edit the message, then press ENTER"
echo "   - Press Ctrl+C to cancel"
echo ""
echo "Let's see it in action! (Note: This is a demo, actual usage varies by terminal)"
echo ""
echo "Example flow:"
echo "============="
echo ""
echo "$ git add ."
echo "$ aicom"
echo ""
echo "✨ Generating commit message... ⠋"
echo ""
echo "📝 Commit message: feat: add user authentication with JWT tokens"
echo "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "                   (This text is editable! Just start typing or press Enter)"
echo ""
echo "[User presses Enter]"
echo ""
echo "[main abc1234] feat: add user authentication with JWT tokens"
echo " 3 files changed, 127 insertions(+), 12 deletions(-)"
echo "✅ Committed successfully!"
echo ""
echo "---"
echo ""
echo "💡 Pro tip: The message is pre-filled with the AI suggestion,"
echo "   so you can quickly edit any part before committing!"
